#!/usr/bin/env python3
"""Renders the screen's text on the host into src/UiAssets.cpp.

The board never sees the font. Text is drawn here with Pillow, from
assets/fonts/Inter[opsz,wght].ttf (SIL OFL), into 8-bit alpha masks that
lib/Compose blends in any color. The look follows the prototype
(tools/prototype/dice.html): thin letters, captions in spaced capitals.

Run after changing any text or the font:

    python3 tools/make_ui_assets.py

Needs Pillow.
"""

import math
import pathlib

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT = ROOT / "assets/fonts/Inter[opsz,wght].ttf"
OUTPUT = ROOT / "src/UiAssets.cpp"

# Drawn this many times larger and scaled down: smooth edges.
SUPERSAMPLE = 4

# (field, text, size in px, weight). Spaces stand in for letter spacing, as
# in the prototype.
CAPTIONS = [
    ("title", "D  I  C  E", 15, 300),
    ("pressOrShake", "P R E S S   O R   S H A K E", 10, 400),
    ("oneDie", "O N E   D I E", 10, 400),
    ("twoDice", "T W O   D I C E", 10, 400),
]
TOAST_DIGITS = ("1", "2")
TOAST_SIZE, TOAST_WEIGHT = 64, 200
PILL_GLYPHS = "0123456789+="
PILL_SIZE, PILL_WEIGHT = 17, 300


def font(size, weight):
    f = ImageFont.truetype(str(FONT), size * SUPERSAMPLE)
    # Optical size: the small cuts are sturdier, the big one finer.
    f.set_variation_by_axes([max(14, min(32, size)), weight])
    return f


def render(text, size, weight, crop_x=True):
    """Returns (width, height, baseline row, alpha bytes)."""
    f = font(size, weight)
    ascent, descent = f.getmetrics()
    pad = 2 * SUPERSAMPLE
    base = pad + SUPERSAMPLE * math.ceil(ascent / SUPERSAMPLE)
    advance = f.getlength(text)
    width = pad * 2 + SUPERSAMPLE * math.ceil(advance / SUPERSAMPLE)
    height = base + SUPERSAMPLE * math.ceil(descent / SUPERSAMPLE) + pad
    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((pad, base), text, font=f, fill=255, anchor="ls")
    small = image.reduce(SUPERSAMPLE)
    baseline = base // SUPERSAMPLE
    left, top, right, bottom = small.getbbox()
    if not crop_x:
        # Keep the advance: glyphs are laid out by their cell widths.
        left = pad // SUPERSAMPLE
        right = left + round(advance / SUPERSAMPLE)
    small = small.crop((left, top, right, bottom))
    return small.width, small.height, baseline - top, small.tobytes()


def mode_square(filled):
    s = SUPERSAMPLE
    image = Image.new("L", (10 * s, 10 * s), 0)
    draw = ImageDraw.Draw(image)
    if filled:
        draw.rounded_rectangle((s // 2, s // 2, 10 * s - s // 2 - 1, 10 * s - s // 2 - 1),
                               radius=2 * s, fill=255)
    else:
        draw.rounded_rectangle((0, 0, 10 * s - 1, 10 * s - 1), radius=2 * s + s // 2,
                               outline=255, width=s)
    small = image.reduce(s)
    return small.width, small.height, 0, small.tobytes()


def c_array(name, data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 24]) + ",")
    return "const uint8_t %s[] = {\n%s\n};\n" % (name, "\n".join(lines))


def main():
    arrays = []
    fields = {}

    def add(field, mask, array_name=None):
        w, h, baseline, data = mask
        name = array_name or "k" + field[0].upper() + field[1:]
        arrays.append(c_array(name, data))
        return "{%d, %d, %d, %s}" % (w, h, baseline, name)

    for field, text, size, weight in CAPTIONS:
        fields[field] = add(field, render(text, size, weight))
    fields["toastDigit"] = "{%s}" % ", ".join(
        add("toastDigit", render(d, TOAST_SIZE, TOAST_WEIGHT), "kToastDigit" + d)
        for d in TOAST_DIGITS)
    names = {"+": "Plus", "=": "Equals"}
    fields["pillGlyph"] = "{%s}" % ", ".join(
        add("pillGlyph", render(g, PILL_SIZE, PILL_WEIGHT, crop_x=False),
            "kPill" + names.get(g, g))
        for g in PILL_GLYPHS)
    fields["modeOn"] = add("modeOn", mode_square(True))
    fields["modeOff"] = add("modeOff", mode_square(False))

    f = font(PILL_SIZE, PILL_WEIGHT)
    top, bottom = f.getbbox("0", anchor="ls")[1], f.getbbox("0", anchor="ls")[3]
    cap_height = round((bottom - top) / SUPERSAMPLE)
    space = round(f.getlength(" ") / SUPERSAMPLE)

    out = [
        "// Generated by tools/make_ui_assets.py from assets/fonts/Inter[opsz,wght].ttf",
        "// (SIL Open Font License). Do not edit by hand.",
        "",
        '#include "UiAssets.h"',
        "",
        "namespace {",
        "",
    ]
    out += arrays
    out += [
        "} // namespace",
        "",
        "const UiAssets kUiAssets = {",
    ]
    order = ["title", "pressOrShake", "oneDie", "twoDice", "toastDigit", "pillGlyph",
             "modeOn", "modeOff"]
    out += ["    %s," % fields[k] for k in order]
    out += ["    %d, // pill digit height" % cap_height,
            "    %d, // pill space" % space,
            "};", ""]
    OUTPUT.write_text("\n".join(out))
    print("wrote", OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
