#pragma once

#include <stdint.h>

#include "Compose.h"
#include "DiceApp.h"
#include "DiceRaster.h"

// The screen's text, generated by tools/make_ui_assets.py (src/UiAssets.cpp).
struct UiAssets {
    AlphaMask title;        // "D I C E" on the splash
    AlphaMask pressOrShake; // the hint
    AlphaMask oneDie;       // the mode switch notice
    AlphaMask twoDice;
    AlphaMask toastDigit[2]; // big thin "1" and "2"
    AlphaMask pillGlyph[12]; // "0".."9", "+", "=" for the result, by advance
    AlphaMask modeOn;        // the mode squares in the corner
    AlphaMask modeOff;
    int16_t pillDigitHeight;
    int16_t pillSpace;
};

// Composes whole frames from DiceViews: the felt and the dice from
// DiceRaster, the text and shapes from Compose, laid out as in the
// prototype. It decides how much to redraw:
//
// - moving dice: one sample per pixel, only around where the dice were and
//   are;
// - dice come to rest: the full screen once, the dice at four samples per
//   pixel, kept in sceneCopy;
// - only the text changes (the result fading in, the toast): sceneCopy
//   restored and the text drawn again.
//
// compose() returns the rectangle that changed, which the caller pushes to
// the display. Hardware-free: the caller owns the buffers.
class DiceScreen {
  public:
    static constexpr int kWidth = DiceRaster::kWidth;
    static constexpr int kHeight = DiceRaster::kHeight;

    struct Buffers {
        uint16_t *frame;      // kWidth * kHeight, the sprite's buffer
        uint16_t *background; // kWidth * kHeight
        uint16_t *sceneCopy;  // kWidth * kHeight
        uint8_t *tile;        // DiceRaster::kTileBytes
    };

    void begin(const Buffers &buffers, const UiAssets *assets);
    Rect compose(const DiceView &v);
    DiceRaster &raster() { return raster_; }

    // Forget the frame: the next compose() redraws everything.
    void invalidate() { valid_ = false; }

  private:
    // What the text depends on; any change means redrawing the text.
    struct UiState {
        Screen screen;
        uint8_t mode;
        bool hint;
        bool result;
        uint8_t values[2];
        uint8_t count;
        uint8_t pillLevel;  // fade-in step, 0..16
        uint8_t toastLevel; // 0..16
    };

    static UiState uiState(const DiceView &v);
    static bool sameUi(const UiState &a, const UiState &b);
    void drawUi(const DiceView &v, const UiState &s, Rect clip);
    void drawPill(const Canvas &c, const UiState &s);
    Rect diceBounds(const DiceView &v) const;
    int centered(const AlphaMask &m) const { return (kWidth - m.width) / 2; }

    DiceRaster raster_;
    Buffers buf_ = {};
    const UiAssets *ui_ = nullptr;

    bool valid_ = false;
    bool lastMoving_ = false;
    Screen lastScreen_ = Screen::Asleep;
    uint32_t lastVersion_ = 0;
    Rect lastDice_ = {0, 0, 0, 0};
    UiState lastUi_ = {};
};
